name: Python package

on:
  schedule:
  - cron:  '* * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run Scripts
      run: |
        python Test.py
    - name: Commit and Push
    - uses: EndBug/add-and-commit@v7
      with:
        message: 'Test commit'
        add: 'Test.txt'
      